server:
  port: ${PORT:8080}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:     postgres://vrmihhqmfsavhc:3a1dc1565432347d50f5cc85dd1a32201807bb55df3e370ae797683cb4b05beb@ec2-52-0-114-209.compute-1.amazonaws.com:5432/d3abjo40es4beb
    username: vrmihhqmfsavhc
    password: 3a1dc1565432347d50f5cc85dd1a32201807bb55df3e370ae797683cb4b05beb

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o Bootcamp DIO - Santander